### ISSUE TITLE
New Gold Images Processing command

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/nautilus-librarian#47]
We are working on a new Typer command:

```
poetry run nautilus-librarian gold-images-processing ...
```

That command represents a GitHub workflow we want to run in a [Media Library](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/.github/workflows/gold-drawings-processing.yml). When we finish this command it will replace all the steps in this [workflow](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/.github/workflows/gold-drawings-processing.yml).

- [x] 1. [Get new or modified Gold images using dvc diff](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/46).
- [x] 2. [Pull images from dvc remote storage](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/55) .
- [x] 3. Validate filenames.
- [x] 4. [Validate file paths](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/48).
- [x] 5. [Validate image size](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/64)
- [x] 6. [Generate Base image from Gold (change size and ICC profile)](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/71).
- [ ] 7. Auto-commit new Base images (PARTIALLY DONE)

Subtask 7 (Auto-commit new Base images) has also subtasks:

- [x] When Gold Image is added
- [ ] [When Gold Image is deleted](https://github.com/Nautilus-Cyberneering/nautilus-librarian/issues/49)
- [ ] When Gold Image is modified. [TBD](https://github.com/Nautilus-Cyberneering/chinese-ideographs/pull/122#issuecomment-972844365).
- [ ] When Gold Image is renamed. [TBD](https://github.com/Nautilus-Cyberneering/chinese-ideographs/pull/122#issuecomment-972844365)

In this issue #76 we will decide and apply the strategy for DVC diff when a file is modified or renamed.

This issue is the main issue only to track subtasks.

**Comment by yeraydavidrodriguez** [comment]
The auto-commiting of deletion, modifications and renamings is covered by #66 . As the rest of functionality is already done, we can close this issue now.
